system:
  thingName: "GREENGRASS_THING_NAME"
  privateKeyPath: "/greengrass/v2/private.pem.key"
  rootCaPath: "/greengrass/v2/AmazonRootCA1.pem"
  certificateFilePath: "/greengrass/v2/device.pem.crt"
  rootpath: "/greengrass/v2"
services:
  main:
    lifecycle: {}
  aws.greengrass.Nucleus:
    configuration:
      awsRegion: "AWS_REGION"
      iotCredEndpoint: "IOT_CRED_ENDPOINT"
      iotDataEndpoint: "IOT_DATA_ENDPOINT"
      iotRoleAlias: "IOT_ROLE_ALIAS_NAME"
